# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uart.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'uart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuart.proto\x12\x04uart\"]\n\x0bUartMessage\x12)\n\x0c\x64\x61ta_message\x18\x01 \x01(\x0b\x32\x11.uart.DataMessageH\x00\x12\x18\n\x03\x61\x63k\x18\x02 \x01(\x0b\x32\t.uart.AckH\x00\x42\t\n\x07payload\".\n\x0b\x44\x61taMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"*\n\x03\x41\x63k\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x10\n\x08response\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UARTMESSAGE']._serialized_start=20
  _globals['_UARTMESSAGE']._serialized_end=113
  _globals['_DATAMESSAGE']._serialized_start=115
  _globals['_DATAMESSAGE']._serialized_end=161
  _globals['_ACK']._serialized_start=163
  _globals['_ACK']._serialized_end=205
# @@protoc_insertion_point(module_scope)
